export const GET_ROOM_DETAIL_REQUEST = "GET_ROOM_DETAIL_REQUEST";
export const GET_ROOM_DETAIL_SUCCESS = "GET_ROOM_DETAIL_SUCCESS";
export const GET_ROOM_DETAIL_FAILED = "GET_ROOM_DETAIL_FAILED";

export const GET_USERS_REQUEST = "GET_USERS_SUCCESS";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAILED = "GET_USERS_FAILED";

export const ADD_NEW_MESSAGE = "ADD_NEW_MESSAGE";
export const GET_OLD_MESSAGE_REQUEST = "GET_OLD_MESSAGE_REQUEST";
export const GET_OLD_MESSAGE_SUCCESS = "GET_OLD_MESSAGE_SUCCESS";
export const GET_OLD_MESSAGE_FAILED = "GET_OLD_MESSAGE_FAILED";

export const SET_CHARACTER = "SET_CHARACTER";

export const JOIN_ROOM_REQUEST = "JOIN_ROOM_REQUEST";
export const JOIN_ROOM_SUCCESS = "JOIN_ROOM_SUCCESS";
export const JOIN_ROOM_FAILED = "JOIN_ROOM_FAILED";