export const GET_ROOM_DETAIL_REQUEST = "GET_ROOM_DETAIL_REQUEST";
export const GET_ROOM_DETAIL_SUCCESS = "GET_ROOM_DETAIL_SUCCESS";
export const GET_ROOM_DETAIL_FAILED = "GET_ROOM_DETAIL_FAILED";

export const SET_READY_TO_JOIN = "SET_READY_TO_JOIN";

export const ADD_NEW_MESSAGE = "ADD_NEW_MESSAGE";

export const SET_CHARACTER = "SET_CHARACTER";

export const JOIN_ROOM_REQUEST = "JOIN_ROOM_REQUEST";
export const JOIN_ROOM_SUCCESS = "JOIN_ROOM_SUCCESS";
export const JOIN_ROOM_FAILED = "JOIN_ROOM_FAILED";

export const ADD_NEW_USER_TO_ROOM = "ADD_NEW_USER_TO_ROOM";
export const REMOVE_USER_IN_ROOM = "REMOVE_USER_IN_ROOM";


export const GET_USERS_IN_ROOM_REQUEST = "GET_USERS_IN_ROOM_REQUEST";
export const GET_USERS_IN_ROOM_SUCCESS = "GET_USERS_IN_ROOM_SUCCESS";
export const GET_USERS_IN_ROOM_FAILED = "GET_USERS_IN_ROOM_FAILED";

export const GET_MESSAGES_REQUEST = "GET_MESSAGES_REQUEST";
export const GET_MESSAGES_SUCCESS = "GET_MESSAGES_SUCCESS";
export const GET_MESSAGES_FAILED = "GET_MESSAGES_FAILED";

export const GET_FILES_REQUEST = "GET_FILES_REQUEST";
export const GET_FILES_SUCCESS = "GET_FILES_SUCCESS";
export const GET_FILES_FAILED = "GET_FILES_FAILED";
export const GET_FILES_LAST_SUCCESS = "GET_FILES_LAST_SUCCESS";
export const ADD_NEW_FILES = "ADD_NEW_FILES";