export const ADD_NEW_USER_TO_ROOM = "ADD_NEW_USER_TO_ROOM";
export const REMOVE_USER_IN_ROOM = "REMOVE_USER_IN_ROOM";


export const JOIN_ROOM_REQUEST = "JOIN_ROOM_REQUEST";
export const JOIN_ROOM_SUCCESS = "JOIN_ROOM_SUCCESS";
export const JOIN_ROOM_FAILED = "JOIN_ROOM_FAILED";

export const GET_USERS_IN_ROOM_REQUEST = "GET_USERS_IN_ROOM_REQUEST";
export const GET_USERS_IN_ROOM_SUCCESS = "GET_USERS_IN_ROOM_SUCCESS";
export const GET_USERS_IN_ROOM_FAILED = "GET_USERS_IN_ROOM_FAILED";

export const GET_MESSAGES_REQUEST = "GET_MESSAGES_REQUEST";
export const GET_MESSAGES_SUCCESS = "GET_MESSAGES_SUCCESS";
export const GET_MESSAGES_FAILED = "GET_MESSAGES_FAILED";

export const ADD_NEW_MESSAGE = "ADD_NEW_MESSAGE";