export const GET_MY_ROOMS_REQUEST = "GET_MY_ROOMS_REQUEST";
export const GET_MY_ROOMS_SUCCESS = "GET_MY_ROOMS_SUCCESS";
export const GET_MY_ROOMS_FAILED = "GET_MY_ROOMS_FAILED";

export const GET_WORLD_ROOMS_REQUEST = "GET_WORLD_ROOMS_REQUEST";
export const GET_WORLD_ROOMS_SUCCESS = "GET_WORLD_ROOMS_SUCCESS";
export const GET_WORLD_ROOMS_FAILED = "GET_WORLD_ROOMS_FAILED";

export const DELETE_ROOM_REQUEST = "DELETE_ROOM_REQUEST";
export const DELETE_ROOM_SUCCESS = "DELETE_ROOM_SUCCESS";
export const DELETE_ROOM_FAILED = "DELETE_ROOM_FAILED";

export const CREATE_ROOM_REQUEST = "CREATE_ROOM_REQUEST";
export const CREATE_ROOM_SUCCESS = "CREATE_ROOM_SUCCESS";
export const CREATE_ROOM_FAILED = "CREATE_ROOM_FAILED";